In [1]:
import numpy as np

In [2]:
array1 = np.array([0,1,2,3,4,5,6,7,8,9])

In [3]:
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
array1 * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
array1 / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

---

기본 파이썬과 달리 바로 연산자 이용 가능

In [8]:
array2 = np.array([2,4,6,8,10,12,14,16,18,20])

In [9]:
array2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [10]:
array1 * array2

array([  0,   4,  12,  24,  40,  60,  84, 112, 144, 180])