In [1]:
import numpy as np

In [2]:
array1 = np.array([1,2,3,4,5,6,7,8,9])

In [3]:
array1[4]

5

In [4]:
array1[[1,3,4]]

array([2, 4, 5])

In [5]:
array2 = np.array([2,1,3])

In [6]:
array2

array([2, 1, 3])

In [7]:
array1[array2]

array([3, 2, 4])

In [8]:
array1[2:7]

array([3, 4, 5, 6, 7])

인덱스 2번부터 인덱스 6번까지

In [9]:
array1[2:7:2]

array([3, 5, 7])

마지막 콜론: 뛰어넘기